---
branches:
  only:
    - master

language: ruby

bundler_args: '--without development system_tests'

before_install:
  - 'gem update --system $RUBYGEMS_VERSION'
  - 'gem update bundler'

script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'

matrix:
  fast_finish: true
  include:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes" RUBYGEMS_VERSION=2.7.8
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"

notifications:
  email: false
